<script setup lang="ts">
import { computed, ref } from 'vue'
import { useAppStore } from '../stores/app'
const store = useAppStore(); const teamName=ref(''); const categoryId=ref('infantil'); const helperId=ref(''); const selectedTeam=ref(''); const participantName=ref(''); const birthDate=ref(''); const showTeam=ref(false)
const grouped = computed(() => store.data.categories.map(category => ({ category, teams: store.data.teams.filter(team => team.category_id === category.id) })))
const participantTeam = computed(() => store.data.teams.find(t => t.id === selectedTeam.value))
async function addTeam(){ await store.save('/api/teams',{name:teamName.value,categoryId:categoryId.value,helperId:helperId.value||null}); teamName.value=''; showTeam.value=false }
async function addParticipant(){ if(!selectedTeam.value)return; await store.save('/api/participants',{name:participantName.value,birthDate:birthDate.value,teamId:selectedTeam.value,status:'titular',position:store.data.participants.filter(p=>p.team_id===selectedTeam.value).length}); participantName.value='';birthDate.value='' }
</script>
<template><section><div class="page-heading"><div><p class="eyebrow">Inscrições</p><h1>Equipes e participantes</h1><p>Organize cada categoria e mantenha a ordem dos competidores.</p></div><button class="primary" @click="showTeam=!showTeam">+ Nova equipe</button></div>
  <form v-if="showTeam" class="panel form-grid three" @submit.prevent="addTeam"><label>Nome da equipe<input v-model="teamName" required></label><label>Categoria<select v-model="categoryId"><option v-for="c in store.data.categories" :value="c.id">{{ c.name }}</option></select></label><label>Auxiliar<select v-model="helperId"><option value="">Sem auxiliar</option><option v-for="h in store.data.helpers" :value="h.id">{{h.name}}</option></select></label><button class="primary">Salvar equipe</button></form>
  <div class="category-columns"><article v-for="group in grouped" :key="group.category.id" class="panel category-card"><div class="category-title"><span></span><div><h2>{{group.category.name}}</h2><small>{{group.category.description}}</small></div></div><button v-for="team in group.teams" :key="team.id" class="team-row" @click="selectedTeam=team.id"><div><strong>{{team.name}}</strong><small>{{store.data.participants.filter(p=>p.team_id===team.id).length}} participantes</small></div><span>›</span></button><div v-if="!group.teams.length" class="empty small">Nenhuma equipe</div></article></div>
  <div v-if="selectedTeam" class="modal-backdrop" @click.self="selectedTeam=''" role="dialog"><section class="modal"><button class="close" @click="selectedTeam=''">×</button><p class="eyebrow">Equipe</p><h2>{{participantTeam?.name}}</h2><div class="participants"><div v-for="p in store.data.participants.filter(p=>p.team_id===selectedTeam)" class="person-row"><span class="avatar">{{p.position+1}}</span><div><strong>{{p.name}}</strong><small>{{p.birth_date}} · {{p.status}}</small></div></div></div><form class="form-stack" @submit.prevent="addParticipant"><h3>Adicionar participante</h3><label>Nome<input v-model="participantName" required></label><label>Data de nascimento<input v-model="birthDate" type="date" required></label><button class="primary wide">Adicionar</button></form></section></div>
</section></template>
